spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?createDatabaseIfNotExist=true
    username: root
    password: Sonu123@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: payment-service
server:
  port: 8085

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"