spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?createDatabaseIfNotExist=true
    username: root
    password: Sonu123@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: course-service
server:
  port: 8082